Don't inherit autotools when configure file doesn't exist
ERROR: satpi-git-r0 do_configure: no configure script found at ./configure
ERROR: udpxy-1+git-r0 do_configure: no configure script found at ./configure
ERROR: dvblast-git-r0 do_configure: no configure script found at ./configure

https://git.openembedded.org/openembedded-core/commit/?id=6d327a39befae44a88a812bdf4acde800dcee57b